/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import conexion.ConexionBD;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Rojeru San
 */
public class Dashboard extends javax.swing.JInternalFrame {

    SimpleDateFormat formato;
    String fecha1, fecha2;

    public Dashboard() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        dashboardLinealDia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelDashboard = new javax.swing.JPanel();
        panelCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCabecera1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelCabecera3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelCabecera4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(58, 159, 171));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/report/icon-dashboard.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 869, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(787, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelDashboard.setLayout(new java.awt.BorderLayout());

        panelCabecera.setBackground(new java.awt.Color(52, 122, 184));
        panelCabecera.setPreferredSize(new java.awt.Dimension(223, 99));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Objetivo producción");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("25,000");

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panelCabecera1.setBackground(new java.awt.Color(93, 184, 91));
        panelCabecera1.setPreferredSize(new java.awt.Dimension(223, 99));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("13,512");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Producción actual");

        javax.swing.GroupLayout panelCabecera1Layout = new javax.swing.GroupLayout(panelCabecera1);
        panelCabecera1.setLayout(panelCabecera1Layout);
        panelCabecera1Layout.setHorizontalGroup(
            panelCabecera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabecera1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabecera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelCabecera1Layout.setVerticalGroup(
            panelCabecera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabecera1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        panelCabecera3.setBackground(new java.awt.Color(239, 173, 77));
        panelCabecera3.setPreferredSize(new java.awt.Dimension(223, 99));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("11,488");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Producción faltante");

        javax.swing.GroupLayout panelCabecera3Layout = new javax.swing.GroupLayout(panelCabecera3);
        panelCabecera3.setLayout(panelCabecera3Layout);
        panelCabecera3Layout.setHorizontalGroup(
            panelCabecera3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabecera3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabecera3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelCabecera3Layout.setVerticalGroup(
            panelCabecera3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabecera3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        panelCabecera4.setBackground(new java.awt.Color(217, 83, 80));
        panelCabecera4.setPreferredSize(new java.awt.Dimension(223, 99));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Producción");

        javax.swing.GroupLayout panelCabecera4Layout = new javax.swing.GroupLayout(panelCabecera4);
        panelCabecera4.setLayout(panelCabecera4Layout);
        panelCabecera4Layout.setHorizontalGroup(
            panelCabecera4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabecera4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        panelCabecera4Layout.setVerticalGroup(
            panelCabecera4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabecera4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(panelCabecera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(panelCabecera3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(panelCabecera4, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCabecera1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabecera3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabecera4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dashboardIncio() {
        try {
            String query = "SELECT fecha,total from ventas";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(ConexionBD.conexion(), query);
//        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
//        barChartData.setValue(20000, "Ventas mensuales", "Enero");
//        barChartData.setValue(30000, "Ventas mensuales", "Febrero");
//        barChartData.setValue(80000, "Ventas mensuales", "Marzo");
//        barChartData.setValue(10000, "Ventas mensuales", "Abril");

            JFreeChart barChart = ChartFactory.createLineChart("Ventas mensuales", "total", "fecha", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot catPlot = barChart.getCategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);

            ChartPanel barPanel = new ChartPanel(barChart);
            panelDashboard.removeAll();
            panelDashboard.add(barPanel, BorderLayout.NORTH);
            panelDashboard.validate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void dashboardLinealDia() {
//        formato = new SimpleDateFormat("dd/MM/yyyy");
//        fecha1 = formato.format(fechaInicio.getDate());
//        System.out.println(fecha1);
//        fecha2 = formato.format(fechaFin.getDate());
//        System.out.println(fecha2);
        
        try{

            String consulta = "SELECT case MONTH(fecha) \n" +
                                "when 01 then 'Enero' \n" +
                                "when 02 then 'Febrero' \n" +
                                "when 03 then 'Marzo' \n" +
                                "when 04 then 'Abril' \n" +
                                "when 05 then 'Mayo' \n" +
                                "when 06 then 'Junio' \n" +
                                "when 07 then 'Julio' \n" +
                                "when 08 then 'Agosto' \n" +
                                "when 09 then 'Setiembre' \n" +
                                "when 10 then 'Octubre' \n" +
                                "when 11 then 'Noviembre' \n" +
                                "when 12 then 'Diciembre' \n" +
                                "end, SUM(total) as Total FROM ventas WHERE YEAR(fecha)=2018 GROUP BY YEAR(fecha), MONTH(fecha)";

            JDBCCategoryDataset dataset = new JDBCCategoryDataset(ConexionBD.conexion(), consulta);
            JFreeChart barChart = ChartFactory.createLineChart("Ventas mensuales", "Fecha (mes)", "Ventas (soles)", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot catPlot = barChart.getCategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);

            ChartPanel barPanel = new ChartPanel(barChart);
            panelDashboard.removeAll();
            panelDashboard.add(barPanel, BorderLayout.CENTER);
            panelDashboard.validate();
        }catch(Exception e){
            System.out.println(e);
        }

    }

    public void dashboardLinealMes() {
        try {
            String query = "SELECT fecha,total from ventas";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(ConexionBD.conexion(), query);
//        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
//        barChartData.setValue(20000, "Ventas mensuales", "Enero");
//        barChartData.setValue(30000, "Ventas mensuales", "Febrero");
//        barChartData.setValue(80000, "Ventas mensuales", "Marzo");
//        barChartData.setValue(10000, "Ventas mensuales", "Abril");

            JFreeChart barChart = ChartFactory.createLineChart("Ventas mensuales", "total", "fecha", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot catPlot = barChart.getCategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);

            ChartPanel barPanel = new ChartPanel(barChart);
            panelDashboard.removeAll();
            panelDashboard.add(barPanel, BorderLayout.NORTH);
            panelDashboard.validate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void dashboardLinealAño() {
        try {
            String query = "SELECT fecha,total from ventas";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(ConexionBD.conexion(), query);
//        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
//        barChartData.setValue(20000, "Ventas mensuales", "Enero");
//        barChartData.setValue(30000, "Ventas mensuales", "Febrero");
//        barChartData.setValue(80000, "Ventas mensuales", "Marzo");
//        barChartData.setValue(10000, "Ventas mensuales", "Abril");

            JFreeChart barChart = ChartFactory.createLineChart("Ventas mensuales", "total", "fecha", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot catPlot = barChart.getCategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);

            ChartPanel barPanel = new ChartPanel(barChart);
            panelDashboard.removeAll();
            panelDashboard.add(barPanel, BorderLayout.NORTH);
            panelDashboard.validate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCabecera1;
    private javax.swing.JPanel panelCabecera2;
    private javax.swing.JPanel panelCabecera3;
    private javax.swing.JPanel panelCabecera4;
    private javax.swing.JPanel panelDashboard;
    // End of variables declaration//GEN-END:variables
}
